name: 🔂 Surge PR Preview

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
  push:
    paths:
      - docs/**

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: afc163/surge-preview@v1
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dist: /docs/.output/public
          teardown: 'true'
          build: |
            cd ./docs
            yarn install --frozen-lockfile
            npx nuxi generate
      - name: Get the preview_url
        run: echo "url => ${{ steps.preview_step.outputs.preview_url }}"