name: 🔂 CloudFlare Pages Preview

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
  push:
    paths:
      - docs/**

jobs:
  preview:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v3

      - run: | 
              yarn install --frozen-lockfile
              npx nuxi generate
        working-directory: ./docs

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: docker-php
          directory: docs/.output/public
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}